#!/bin/bash

echo "# Generated by github.com/zxyle/dotfiles" >> /etc/resolv.conf
cp /etc/resolv.conf /etc/resolv.conf.bak
echo "nameserver 223.5.5.5" >> /etc/resolv.conf
echo "nameserver 223.6.6.6" >> /etc/resolv.conf